name: Deploy
on:
  push:
    branches: [main]
  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: npm ci
        - run: npm run build
        - run: git --work-tree build add --all
        - run: git -c user.name=Robot -c user.email=nobody@sibr.dev commit -m "Automatic deploy"
        - run: git push origin HEAD:gh-pages --force
